### ISSUE TITLE
Config/Ability to create additional rarities

### ISSUE THREAD

**Issue by Tenuuu** [Gauraaaaaaaa/RankingOfThings#3]
Would be a cool option to allow modpack creators to create additional rarities or change the name of the currently implemented rarities. Unsure if this would be out of the scope for your project, but I thought it would be a nice idea to put out there. 

Great mod by the way! Loving the current implementation and configuration

**Comment by Gauraaaaaaaa** [comment]
Hi!

I'm currently working on it (sorry for the long time).
Why do you need to change the names of the rarities?
Is it because you need to use the names somewhere else? Or is it just to be clearer in the config file?
Because if it's for reason number one, I can't find any possible way to do so...
But for the second reason, I can just put more rarities (like RarityOne, RarityTwo, RarityThree, etc...) and then in
the config file you will just need to indicate the color and the items it should be applied to.

Thank you for your return!

**Comment by Tenuuu** [comment]
Yeah I was more so trying to explain that I wanted the 2nd implementation you mentioned. Having those rarities would help me out for my modpack, but if it is out of the scope for your mod, then no worries!

**Comment by Gauraaaaaaaa** [comment]
Hi!

I tried many things but none of them seems to work properly...
So, I just added more rarities (One, Two, Three, ..., Ten), and you can assign each rarity a color and a list of items (plus the name for clarity).

Hope this will help for your modpack!

**Comment by Tenuuu** [comment]
This solution works perfectly! Thank you so much for the update!
